### ISSUE TITLE
reading UTF-8 encoded entries

### ISSUE THREAD

**Issue by pbochenski** [madhatter22/LinqToLdap#6]
Hi,
I have a user that has some utf-8 encoded names (see ADSI preview, the string is "Jimåäö")
[PREVIEW](https://imgur.com/3fDwGL0)

when tried to read it using annotation it crashed with exception:

> System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.InvalidCastException : Unable to cast object of type 'System.Byte[]' to type 'System.String' at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at LinqToLdap.QueryCommands.StandardQueryCommand.HandleStandardRequest(DirectoryConnection connection, ILinqToLdapLogger log, Int32 maxSize, Boolean pagingEnabled)
   at LinqToLdap.QueryCommands.StandardQueryCommand.Execute(DirectoryConnection connection, SearchScope scope, Int32 maxPageSize, Boolean pagingEnabled, ILinqToLdapLogger log, String namingContext)
   at LinqToLdap.DirectoryQueryProvider.Execute(Expression expression)
   at LinqToLdap.QueryProvider.Execute[TResult](Expression expression)
   at LinqToLdap.QueryableExtensions.ToList[TSource](IQueryable`1 source)
   at ******.DirectoryCollectionInternal`2.ToList()

So I added custom mapper and it turned out that byte[] that is passed to mapper is UTF-7 encoded. Any reason why this is not UTF-8?

**Comment by pbochenski** [comment]
turned out I have had bug in my code. no issue in the library :)
